- name:
  hosts: local
  connection: local # managing its own node, no need of credentials
  tasks:
  - name: PLAY1 and TASK1
    ansible.builtin.debug:
      msg: "hello from PLAY1 and TASK1"

- name: PLAY2
  hosts: local
  connection: local
  tasks:
  - name: PLAY2 and TASK1
  ansible.builtin.debug:
    msg: "helloo from PLAY2 and TASK1"