- name: variable
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: "120HRS"
    TRAINER: "SAI SANDEEP"
  tasks:
  - name: print variables
    vars:
      COURSE: "ANSIBLE"
    ansible.builtin.debug:
      msg: "course is {{COURSE}} for {{DURATION}}, trainer is {{TRAINER}}"