- name: 
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
  - name: DURATION
    prompt: please enter duration
  - name: TRAINER
    prompt: please enter trainer name
  tasks:
  - name: print course details
    ansible.builtin.plugin:
      msg: "course is {{COURSE}} for {{DURATION}} and trainer is {{TRAINER}}"
