- name: variables from arguments
  hosts: local
  connection: local
  tasks: 
  - name: print course details
    ansible.builtin.debug:
      msg: "course is {{COURSE}} for duration of {{DURATION}} and trainer is {{TRAINER}}"