- name: check value is greater than 10 or not
  hosts: local
  connection: local
  vars:
    my_number: 5
  tasks:
  - name: print if number greater than 10
    ansible.builtin.debug:
      msg: "Given number {{my_number}} is greater than 10"
    when: my_number > 10

  - name: print if number lessthan 10
    ansible.builtin.debug:
      msg: "Given number {{my_number}} is lessthan 10"
    when: my_number < 10
